language: php

php:
  - 5.4

env:
 - DB=mysql

before_install:
 - 'wget http://pecl.php.net/get/APC ; tar -xzf APC ; sh -c "cd APC-* && phpize && ./configure  && make && sudo make install" ; echo "extension=apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`'
 - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS blogbeartest;USE blogbeartest;CREATE TABLE IF NOT EXISTS posts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(50),body TEXT,created DATETIME DEFAULT NULL,modified DATETIME DEFAULT NULL);" -u root; fi
 - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS blogbear;USE blogbear;CREATE TABLE IF NOT EXISTS posts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(50),body TEXT,created DATETIME DEFAULT NULL,modified DATETIME DEFAULT NULL);" -u root; fi
 - composer install
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
 - pear config-set auto_discover 1
 - pear install pear.phpunit.de/PHP_Invoker
 - pear install pear.phpunit.de/DbUnit
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install -dev

script:
 - phpunit --coverage-text
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  email: false
